messages:
    not-from-console: '&cYou must be a player to perform that command.'
    operation-cancelled: '&cOperation cancelled.'
    payment-usage: '&cUsage: /payment [create|invite|kick|join|leave|withdraw|deposit|list|info|set]'
    payment-create-valid: '&aPayment group created.'
    payment-create-usage: '&cUsage: /payment create [group]'
    payment-invite-valid: '&aInvitation sent to character.'
    payment-invite-invalid-character: '&cThat player does not have an active character.'
    payment-invite-invalid-group: '&cThere is no payment group by that name.'
    payment-invite-usage: '&cUsage: /payment invite [group] [player]'
    payment-kick-valid: '&aCharacter kicked from payment group.'
    payment-kick-invalid-character: '&cThat player does not have an active character.'
    payment-kick-usage: '&cUsage: /payment kick [group] [player]'
    payment-join-valid: '&aJoined payment group.'
    payment-join-invalid-invite: '&cYou must have an invite to join a payment group.'
    payment-join-invalid-character: '&cYou must have a character in order to join a payment group.'
    payment-join-invalid-group: '&cThere is no payment group by that name.'
    payment-join-usage: '&cUsage: /payment join [group]'
    payment-leave-valid: '&aLeft payment group.'
    payment-leave-invalid-member: '&cYou are not a member of that payment group.'
    payment-leave-invalid-character: '&cYou must have a character in order to leave a payment group.'
    payment-leave-invalid-group: '&cThere is no payment group by that name.'
    payment-leave-usage: '&cUsage: /payment leave [group]'
    payment-withdraw-valid: '&aWithdrew money from the payment group.'
    payment-withdraw-invalid-amount: '&cYou must specify a positive amount to withdraw. If you wish to deposit instead, use /payment deposit.'
    payment-withdraw-invalid-currency: '&cThat payment group doesn''t yet have a currency set, so it is impossible to withdraw money.'
    payment-withdraw-invalid-group: '&cThere is no payment group by that name.'
    payment-withdraw-invalid-character: '&cYou must have an active character in order to withdraw money from a payment group.'
    payment-withdraw-usage: '&cUsage: /payment withdraw [group] [amount]'
    payment-deposit-valid: '&aDeposited money to the payment group.'
    payment-deposit-invalid-amount: '&cYou must specify a positive amount to deposit. If you wish to withdraw instead, use /payment withdraw.'
    payment-deposit-invalid-currency: '&cThat payment group doesn''t yet have a currency set, so it is impossible to deposit money.'
    payment-deposit-invalid-group: '&cThere is no payment group by that name.'
    payment-deposit-invalid-character: '&cYou must have an active character in order to deposit money into a payment group.'
    payment-deposit-usage: '&cUsage: /payment deposit [group] [amount]'
    payment-list-title: '&fPayment groups:'
    payment-list-item: '&f- &7$name &f(&7$rank&f)'
    payment-info:
    - '&7$name (&a&l$edit(name)&7)'
    - '&7Owners: &f$owners'
    - '&7Members: &f$members'
    - '&7Invites: &f$invites'
    - '&7Amount: &f$amount &7(&a&l$edit(amount)&7)'
    - '&7Currency: &f$currency &7(&a&l$edit(currency)&7)'
    - '&7Interval: &f$interval &7(&a&l$edit(interval)&7)'
    - '&7Last payment time: &f$last-payment-time'
    - '&7Balance: &f$balance'
    payment-info-invalid-group: '&cThere is no payment group by that name.'
    payment-info-usage: '&cUsage: /payment info [group]'
    payment-set-amount-invalid-owner: '&cYou must be an owner of the payment group in order to set the amount.'
    payment-set-amount-invalid-group: '&cNo group by that name exists.'
    payment-set-amount-usage: '&cUsage: /payment set amount [group]'
    payment-set-amount-prompt: '&fWhat would you like to set the amount paid out to be? Use negative amounts to make characters pay in to the group instead of being paid. &7(Type cancel to cancel)'
    payment-set-amount-invalid-number: '&cYou must specify a number for the amount.'
    payment-set-amount-valid: '&aAmount set.'
    payment-set-currency-invalid-owner: '&cYou must be an owner of the payment group in order to set the currency.'
    payment-set-currency-invalid-group: '&cNo group by that name exists.'
    payment-set-currency-usage: '&cUsage: /payment set currency [group]'
    payment-set-currency-prompt: '&fWhich currency should transactions be performed in? &7(Type cancel to cancel)'
    payment-set-currency-invalid-currency: '&cYou must specify a valid currency.'
    payment-set-currency-valid: '&aCurrency set.'
    payment-set-interval-invalid-owner: '&cYou must be an owner of the payment group in order to set the name.'
    payment-set-interval-invalid-group: '&cNo group by that name exists.'
    payment-set-interval-usage: '&cUsage: /payment set interval [group]'
    payment-set-interval-prompt: '&fWhat would you like to set the interval between payments to be (in seconds)?  &7(Type cancel to cancel)'
    payment-set-interval-invalid-validation: '&cThe interval must be a positive integer.'
    payment-set-interval-invalid-number: '&cYou must specify a number for the interval.'
    payment-set-interval-valid: '&aInterval set.'
    payment-set-name-invalid-owner: '&cYou must be an owner of the payment group in order to set the name.'
    payment-set-name-invalid-group: '&cNo payment group by that name exists.'
    payment-set-name-usage: '&cUsage: /payment set name [group]'
    payment-set-name-prompt: '&fWhat would you like the name of the payment group to be set to? &7(Type cancel to cancel)'
    payment-set-name-valid: '&aName set.'
    payment-notification-member-fail-to-pay: '&cYou failed to pay to payment group "$group" on $date.'
    payment-notification-owner-fail-to-pay: '&c$member failed to pay to payment group "$group" on $date.'
    payment-notification-member-fail-to-be-paid: '&cPayment group "$group" failed to pay you on $date.'
    payment-notification-owner-fail-to-be-paid: '&cPayment group "$group" failed to pay $member on $date.'
    payment-notification-member-join: '&a$member joined payment group "$group" on $date.'
    payment-notification-member-leave: '&a$member left payment group "$group" on $date.'
    payment-notification-invite: '&aYou were invited to join payment group "$group" on $date.'
    payment-notification-kick: '&cYou were kicked from payment group "$group" on $date.'
    no-permission-payment-set-amount: '&cYou do not have permission to set payment group amounts.'
    no-permission-payment-set-currency: '&cYou do not have permission to set payment group currencies.'
    no-permission-payment-set-interval: '&cYou do not have permission to set payment group intervals.'
    no-permission-payment-set-name: '&cYou do not have permission to set payment group names.'
    no-permission-payment-create: '&cYou do not have permission to create payment groups.'
    no-permission-payment-deposit: '&cYou do not have permission to deposit into payment groups.'
    no-permission-payment-info: '&cYou do not have permission to view information on payment groups.'
    no-permission-payment-invite: '&cYou do not have permission to invite people to payment groups.'
    no-permission-payment-join: '&cYou do not have permission to join payment groups.'
    no-permission-payment-kick: '&cYou do not have permission to kick people from payment groups.'
    no-permission-payment-leave: '&cYou do not have permission to leave payment groups.'
    no-permission-payment-list: '&cYou do not have permission to list payment groups.'
    no-permission-payment-withdraw: '&cYou do not have permission to withdraw from payment groups.'
payment-groups:
    defaults:
        # The amount a payment group should pay.
        # A positive amount pays out to members, whereas a negative amount takes money from members.
        amount: 0
        # How often each payment should happen, measured in milliseconds.
        # The default, 604800000 is one week.
        interval: 604800000