name: elysium-payments-bukkit
author: alyphen
version: @version@
main: com.seventh_root.elysium.payments.bukkit.ElysiumPaymentsBukkit
depend:
- elysium-core-bukkit
- elysium-player-lib-bukkit
- elysium-character-lib-bukkit
- elysium-economy-lib-bukkit
- elysium-bank-lib-bukkit
- elysium-payment-lib-bukkit
commands:
    payment:
        description: Payment management command
        usage: /<command> [set|create|deposit|info|invite|join|kick|leave|list|set|withdraw]
permissions:
    elysium.payments.command.payment.set.amount:
        description: Allows setting payment group amounts where the user is an owner
        default: true
    elysium.payments.command.payment.set.currency:
        description: Allows setting payment group currencies where the user is an owner
        default: true
    elysium.payments.command.payment.set.interval:
        description: Allows setting payment group intervals where the user is an owner
        default: true
    elysium.payments.command.payment.set.name:
        description: Allows setting payment group names where the user is an owner
        default: true
    elysium.payments.command.payment.create:
        description: Allows creating payment groups
        default: true
    elysium.payments.command.payment.deposit:
        description: Allows depositing into a payment group where the user is an owner
        default: true
    elysium.payments.command.payment.info:
        description: Allows displaying information on a payment group
        default: true
    elysium.payments.command.payment.invite:
        description: Allows inviting players to a payment group where the user is an owner
        default: true
    elysium.payments.command.payment.join:
        description: Allows joining payments groups to which the user has been invited
        default: true
    elysium.payments.command.payment.kick:
        description: Allows kicking players from payment groups where the user is an owner
        default: true
    elysium.payments.command.payment.leave:
        description: Allows leaving payment groups which have been joined
        default: true
    elysium.payments.command.payment.list:
        description: Allows listing payment groups which the user is involved in
        default: true
    elysium.payments.command.payment.withdraw:
        description: Allows withdrawing from a payment group where the user is an owner
        default: true
