chat-channels:
    general:
        color:
            red: 170
            green: 170
            blue: 170
        radius: -1
        directed-pipeline:
        - ==: DirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: SendMessageComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: IRCComponent
          irc-channel: '#rpkit-general'
          irc-whitelisted: false
        - ==: LogComponent
        joined-by-default: true
    support:
        color:
            red: 0
            green: 170
            blue: 0
        radius: -1
        directed-pipeline:
        - ==: DirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: SendMessageComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: IRCComponent
          irc-channel: '#rpkit-support'
          irc-whitelisted: false
        - ==: LogComponent
        joined-by-default: true
    staff:
        color:
            red: 170
            green: 0
            blue: 170
        radius: -1
        directed-pipeline:
        - ==: DirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: SendMessageComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: IRCComponent
          irc-channel: '#rpkit-staff'
          irc-whitelisted: false
        - ==: LogComponent
        joined-by-default: false
    say:
        color:
            red: 85
            green: 255
            blue: 85
        radius: 16
        directed-pipeline:
        - ==: RadiusFilterComponent
        - ==: GarbleComponent
          clear-radius: 8
        - ==: DirectedFormatComponent
          format: '$color$sender-character says: &f$message'
        - ==: SendMessageComponent
        - ==: SnoopComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color$sender-character says: &f$message'
        - ==: LogComponent
        joined-by-default: true
    shout:
        color:
            red: 255
            green: 85
            blue: 85
        radius: 32
        directed-pipeline:
        - ==: RadiusFilterComponent
        - ==: GarbleComponent
          clear-radius: 16
        - ==: DirectedFormatComponent
          format: '$color$sender-character shouts: &f$message'
        - ==: SendMessageComponent
        - ==: SnoopComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color$sender-character shouts: &f$message'
        - ==: LogComponent
        joined-by-default: true
    whisper:
        color:
            red: 85
            green: 255
            blue: 255
        radius: 8
        directed-pipeline:
        - ==: RadiusFilterComponent
        - ==: GarbleComponent
          clear-radius: 4
        - ==: DirectedFormatComponent
          format: '$color$sender-character whispers: &f$message'
        - ==: SendMessageComponent
        - ==: SnoopComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color$sender-character whispers: &f$message'
        - ==: LogComponent
        joined-by-default: true
    emote:
        color:
            red: 255
            green: 255
            blue: 85
        radius: 16
        directed-pipeline:
        - ==: RadiusFilterComponent
        - ==: DirectedFormatComponent
          format: '$color&o$sender-character $message'
        - ==: SendMessageComponent
        - ==: SnoopComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color&o$sender-character $message'
        - ==: LogComponent
        match-pattern: '\*([^\*]+)\*?'
        joined-by-default: true
irc:
    enabled: true
    name: 'rpkit'
    real-name: 'rpkit'
    login: 'rpkit'
    cap-enabled: true
    auto-nick-change-enabled: true
    auto-split-message-enabled: false
    server: 'chat.freenode.net:6667'
    password: 'change_me'
prefixes:
    admin: '&e[Admin]'
    mod: '&9[Moderator]'
    dev: '&4[Developer]'
    et: '&3[Event Team]'
chat-group:
    format: '&8[$group] $sender-player: &f$message'
