chat-channels:
    general:
        color:
            red: 170
            green: 170
            blue: 170
        radius: -1
        directed-pipeline:
        - ==: DirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: SendMessageComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: IRCComponent
          irc-channel: '#rpkit-general'
          irc-whitelisted: false
        - ==: LogComponent
        joined-by-default: true
    support:
        color:
            red: 0
            green: 170
            blue: 0
        radius: -1
        directed-pipeline:
        - ==: DirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: SendMessageComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: IRCComponent
          irc-channel: '#rpkit-support'
          irc-whitelisted: false
        - ==: LogComponent
        joined-by-default: true
    staff:
        color:
            red: 170
            green: 0
            blue: 170
        radius: -1
        directed-pipeline:
        - ==: DirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: SendMessageComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color[$channel] $sender-prefix$color$sender-player: &f$message'
        - ==: IRCComponent
          irc-channel: '#rpkit-staff'
          irc-whitelisted: false
        - ==: LogComponent
        joined-by-default: false
    say:
        color:
            red: 85
            green: 255
            blue: 85
        radius: 16
        directed-pipeline:
        - ==: RadiusFilterComponent
        - ==: GarbleComponent
          clear-radius: 8
        - ==: DirectedFormatComponent
          format: '$color$sender-character says: &f$message'
        - ==: SendMessageComponent
        - ==: SnoopComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color$sender-character says: &f$message'
        - ==: LogComponent
        joined-by-default: true
    shout:
        color:
            red: 255
            green: 85
            blue: 85
        radius: 32
        directed-pipeline:
        - ==: RadiusFilterComponent
        - ==: GarbleComponent
          clear-radius: 16
        - ==: DirectedFormatComponent
          format: '$color$sender-character shouts: &f$message'
        - ==: SendMessageComponent
        - ==: SnoopComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color$sender-character shouts: &f$message'
        - ==: LogComponent
        joined-by-default: true
    whisper:
        color:
            red: 85
            green: 255
            blue: 255
        radius: 8
        directed-pipeline:
        - ==: RadiusFilterComponent
        - ==: GarbleComponent
          clear-radius: 4
        - ==: DirectedFormatComponent
          format: '$color$sender-character whispers: &f$message'
        - ==: SendMessageComponent
        - ==: SnoopComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color$sender-character whispers: &f$message'
        - ==: LogComponent
        joined-by-default: true
    emote:
        color:
            red: 255
            green: 255
            blue: 85
        radius: 16
        directed-pipeline:
        - ==: RadiusFilterComponent
        - ==: DirectedFormatComponent
          format: '$color&o$sender-character $message'
        - ==: SendMessageComponent
        - ==: SnoopComponent
        undirected-pipeline:
        - ==: UndirectedFormatComponent
          format: '$color&o$sender-character $message'
        - ==: LogComponent
        match-pattern: '\*([^\*]+)\*?'
        joined-by-default: true
messages:
    chatchannel-valid: '&aNow speaking in $channel.'
    chatchannel-invalid-chatchannel: '&cNo chat channel by that name exists.'
    chatchannel-usage: '&cUsage: /chatchannel [channel]'
    mute-valid: '&aMuted $channel.'
    mute-invalid-chatchannel: '&cNo chat channel by that name exists.'
    mute-usage: '&cUsage: /mute [channel]'
    unmute-valid: '&aUnmuted $channel.'
    unmute-invalid-chatchannel: '&cNo chat channel by that name exists.'
    unmute-usage: '&cUsage: /unmute [channel]'
    listchatchannels-title: '&fChat channels:'
    listchatchannels-item: '&f- $color$channel'
    irc-register-valid: 'Registered. Please check your email for the verification code to complete the verification process.'
    irc-register-invalid-email-invalid: 'You did not specify a valid email.'
    irc-register-invalid-email-not-specified: 'You must specify an email.'
    irc-verify-valid: 'Attempted to verify. If you correctly entered the verification code, I should now be verified.'
    irc-verify-invalid-verification-code-not-specified: 'You must specify the registration code from your email.'
    irc-quit: 'Server shut down.'
    snoop-usage: '&cUsage: /snoop [on|off|check]'
    snoop-enabled: '&aSnooping enabled.'
    snoop-already-enabled: '&cSnooping was already enabled.'
    snoop-disabled: '&aSnooping disabled.'
    snoop-already-disabled: '&cSnooping was already disabled.'
    snoop-check-on: '&aSnooping is enabled.'
    snoop-check-off: '&aSnooping is disabled.'
    chat-group-create-valid: '&aChat group created. Use /chatgroup invite $group [player] to invite players.'
    chat-group-create-invalid-reserved: '&cChat groups starting with _pm_ are reserved. Please choose a different name.'
    chat-group-create-invalid-taken: '&cA chat group by that name already exists. Please choose a different name.'
    chat-group-create-usage: '&cUsage: /chatgroup create [name]'
    chat-group-disband-valid: '&aChat group $group disbanded.'
    chat-group-disband-invalid-nonexistent: '&cNo chat group by that name exists.'
    chat-group-disband-usage: '&cUsage: /chatgroup disband [name]'
    chat-group-invite-received: '&aYou have been invited to chat group $group. Use /chatgroup join $group to join.'
    chat-group-invite-valid: '&aYou invited $player to the chat group $group.'
    chat-group-invite-invalid-player: '&cNo player by that name is online.'
    chat-group-invite-invalid-not-a-member: '&cYou are not a member of that chat group.'
    chat-group-invite-invalid-chat-group: '&cNo chat group by that name exists.'
    chat-group-invite-usage: '&cUsage: /chatgroup invite [name] [player]'
    chat-group-join-received: '&a$player joined $group.'
    chat-group-join-valid: '&aJoined chat group $group.'
    chat-group-join-invalid-no-invite: '&cYou have not been invited to that chat group.'
    chat-group-join-invalid-chat-group: '&cNo chat group by that name exists.'
    chat-group-join-usage: '&cUsage: /chatgroup join [name]'
    chat-group-leave-valid: '&aLeft chat group $group.'
    chat-group-leave-invalid-not-a-member: '&cYou are not a member of that chat group.'
    chat-group-leave-invalid-chat-group: '&cNo chat group by that name exists.'
    chat-group-leave-usage: '&cUsage: /chatgroup leave [name]'
    chat-group-message-invalid-not-a-member: '&cYou are not a member of that chat group.'
    chat-group-message-invalid-chat-group: '&cNo chat group by that name exists.'
    chat-group-message-usage: '&cUsage: /chatgroup message [name] [message]'
    chat-group-members-list-title: '&aMembers:'
    chat-group-members-list-item: '&f- &7$player'
    chat-group-invitations-list-title: '&aPending invitations:'
    chat-group-invitations-list-item: '&f- &7$player'
    chat-group-members-invalid-chat-group: '&cNo chat group by that name exists.'
    chat-group-members-usage: '&cUsage: /chatgroup members [name]'
    chat-group-usage: '&cUsage: /chatgroup [create|disband|invite|join|leave|message|players]'
    reply-usage: '&cUsage: /reply [group] [message]'
    reply-invalid-chat-group: '&cYou have not used a chat group or private messaged anyone recently.'
    message-invalid-target: '&cNo chat group or player by that name exists.'
    message-invalid-self: '&cYou cannot message yourself.'
    message-usage: '&cUsage: /message [target] [message]'
    not-from-console: '&cYou may not use this command from console.'
    no-character: '&cYou do not currently have an active character. Please create one with /character new, or switch to an old one using /character switch.'
    no-chat-channel: '&cYou are not currently speaking in a chat channel. Please list channels with /listchatchannels and then speak in one using /chatchannel [channel].'
    no-permission-chatchannel: '&cYou do not have permission to speak in $channel.'
    no-permission-listchatchannels: '&cYou do not have permission to list chat channels.'
    no-permission-mute: '&cYou do not have permission to mute $channel.'
    no-permission-unmute: '&cYou do not have permission to unmute $channel.'
    no-permission-snoop-on: '&cYou do not have permission to enable snooping.'
    no-permission-snoop-off: '&cYou do not have permission to disable snooping.'
    no-permission-snoop-check: '&cYou do not have permission to check whether you are snooping.'
    no-permission-chat-group: '&cYou do not have permission to use chat group commands.'
    no-permission-chat-group-create: '&cYou do not have permission to create chat groups.'
    no-permission-chat-group-disband: '&cYou do not have permission to disband chat groups.'
    no-permission-chat-group-invite: '&cYou do not have permission to invite people to chat groups.'
    no-permission-chat-group-join: '&cYou do not have permission to join chat groups.'
    no-permission-chat-group-leave: '&cYou do not have permission to leave chat groups.'
    no-permission-chat-group-members: '&cYou do not have permission to list chat group members.'
    no-permission-chat-group-message: '&cYou do not have permission to message chat groups.'
    no-permission-message: '&cYou do not have permission to send private messages.'
    no-permission-reply: '&cYou do not have permission to reply to messages.'
    command-snoop: '&2[command] $sender-player: $command'
irc:
    enabled: true
    name: 'rpkit'
    real-name: 'rpkit'
    login: 'rpkit'
    cap-enabled: true
    auto-nick-change-enabled: true
    auto-split-message-enabled: false
    server: 'chat.freenode.net:6667'
    password: 'change_me'
prefixes:
    admin: '&e[Admin]'
    mod: '&9[Moderator]'
    dev: '&4[Developer]'
    et: '&3[Event Team]'
chat-group:
    format: '&8[$group] $sender-player: &f$message'
