name: elysium-characters-bukkit
version: @version@
main: com.seventh_root.elysium.characters.bukkit.ElysiumCharactersBukkit
author: alyphen
description: Elysium Characters implementation for Bukkit
depend: [elysium-core-bukkit, elysium-player-lib-bukkit, elysium-character-lib-bukkit]
commands:
    character:
        description: Character management command
        aliases: [char, c]
        usage: /<command> [set|card|switch|list|new|delete]
    gender:
        description: Gender management command
        usage: /<command> [add|remove|list]
    race:
        description: Race management command
        usage: /<command> [add|remove|list]
permissions:
    elysium.characters.command.character.card.self:
        description: Allows viewing your own character card
        default: true
    elysium.characters.command.character.card.other:
        description: Allows viewing other character cards
        default: true
    elysium.characters.command.character.list:
        description: Allows viewing your own character list
        default: true
    elysium.characters.command.character.new:
        description: Allows creating a new character
        default: true
    elysium.characters.command.character.set.age:
        description: Allows setting your character''s age
        default: true
    elysium.characters.command.character.set.dead:
        description: Allows setting your character''s dead state
        default: true
    elysium.characters.command.character.set.dead.yes:
        description: Allows setting your character to be dead
        default: true
    elysium.characters.command.character.set.dead.no:
        description: Allows setting your character to be not dead
        default: op
    elysium.characters.command.character.set.description:
        description: Allows setting your character''s description
        default: true
    elysium.characters.command.character.set.gender:
        description: Allows setting your character''s gender
        default: true
    elysium.characters.command.character.set.name:
        description: Allows setting your character''s name
        default: true
    elysium.characters.command.character.set.player:
        description: Allows assigning your characters to a different player
        default: true
    elysium.characters.command.character.set.race:
        description: Allows setting your character''s race
        default: true
    elysium.characters.command.character.switch:
        description: Allows switching to other characters
        default: true
    elysium.characters.command.character.delete:
        description: Allows deleting characters
        default: true
    elysium.characters.command.gender.add:
        description: Allows creation of genders
        default: op
    elysium.characters.command.gender.remove:
        description: Allows removal of genders
        default: op
    elysium.characters.command.gender.list:
        description: Allows listing of genders
        default: true
    elysium.characters.command.race.add:
        description: Allows creation of races
        default: op
    elysium.characters.command.race.remove:
        description: Allows removal of races
        default: op
    elysium.characters.command.race.list:
        description: Allows listing of races
        default: true
