name: rpk-bank-lib-bukkit
author: alyphen
version: @version@
main: com.rpkit.banks.bukkit.RPKBankLibBukkit
depend: [rpk-core-bukkit, rpk-character-lib-bukkit, rpk-economy-lib-bukkit]
softdepend: [Vault]