messages:
    character-usage: '&cUsage: /character [set|card|switch|list|new|delete]'
    character-set-usage: '&cUsage: /character set [player|name|gender|age|race|description|dead]'
    character-set-age-prompt: '&fWhat age is your character? &7(Type cancel to cancel)'
    character-set-age-invalid-validation: '&cAge must be between 0 and 10000 inclusive.'
    character-set-age-invalid-number: '&cAge must be a number.'
    character-set-age-valid: '&aAge set.'
    character-set-dead-prompt: '&fIs your character dead? &7(Type cancel to cancel)'
    character-set-dead-invalid-boolean: '&cThat''s not a valid answer.'
    character-set-dead-valid: '&aDead set.'
    character-set-description-prompt: '&fPlease enter some text to append to your character''s description, or type "end" to end. &7(Type cancel to cancel)'
    character-set-description-valid: '&aDescription set.'
    character-set-player-prompt: '&fWhat player do you want to assign this character to? &7(Type cancel to cancel)'
    character-set-player-invalid-player: '&cThat player is not online.'
    character-set-player-valid: '&aYour character was assigned to a different player. You will now be moved to a new character.'
    character-set-name-prompt: '&fWhat is your character''s name? &7(Type cancel to cancel)'
    character-set-name-valid: '&aName set.'
    character-set-gender-prompt: '&fWhat is your character''s gender? &7(Type cancel to cancel)'
    character-set-gender-invalid-gender: '&cThat''s not a valid gender.'
    character-set-gender-valid: '&aGender set.'
    character-set-race-prompt: '&fWhat is your character''s race? &7(Type cancel to cancel)'
    character-set-race-invalid-race: '&cThat''s not a valid race.'
    character-set-race-valid: '&aRace set.'
    character-hide-age-valid: '&aAge hidden.'
    character-hide-description-valid: '&aDescription hidden.'
    character-hide-player-valid: '&aPlayer hidden.'
    character-hide-name-valid: '&aName hidden.'
    character-hide-gender-valid: '&aGender hidden.'
    character-hide-race-valid: '&aRace hidden.'
    character-unhide-age-valid: '&aAge unhidden.'
    character-unhide-description-valid: '&aDescription unhidden.'
    character-unhide-player-valid: '&aPlayer unhidden.'
    character-unhide-name-valid: '&aName unhidden.'
    character-unhide-gender-valid: '&aGender unhidden.'
    character-unhide-race-valid: '&aRace unhidden.'
    character-card-owner:
    - '&7$name (&a&l$edit(name)&7/&a&l$hide(name)&7)'
    - '&7Player: &f$player'
    - '&7Gender: &f$gender &7(&a&l$edit(gender)&7/&a&l$hide(gender)&7)'
    - '&7Age: &f$age &7(&a&l$edit(age)&7/&a&l$hide(age)&7)'
    - '&7Race: &f$race &7(&a&l$edit(race)&7/&a&l$hide(race)&7)'
    - '&7Description: &f$description &7(&a&l$edit(description)&7/&a&l$hide(description)&7)'
    - '&7Dead: &f$dead &7(&a&l$edit(dead)&7)'
    - '&7Health: &f$health&7/&f$max-health'
    - '&7Food: &f$food&7/&f$max-food'
    - '&7Thirst: &f$thirst&7/&f$max-thirst'
    character-card-not-owner:
    - '&7$name'
    - '&7Player: &f$player'
    - '&7Gender: &f$gender'
    - '&7Age: &f$age'
    - '&7Race: &f$race'
    - '&7Description: &f$description'
    - '&7Dead: &f$dead'
    - '&7Health: &f$health'
    - '&7Food: &f$food&7/&f$max-food'
    - '&7Thirst: &f$thirst&7/&f$max-thirst'
    character-list-title: '&fYour characters: '
    character-list-item: '&f- $character'
    character-switch-prompt: '&fWhat is the name of the character you would like to switch to? &7(Type cancel to cancel)'
    character-switch-invalid-character: '&cYou do not have a character by that name.'
    character-switch-valid: '&aCharacter switched.'
    character-new-valid: '&aCharacter created.'
    character-new-invalid-cooldown: '&cYou may not create another character until the cooldown has passed.'
    character-delete-prompt: '&fWhat is the name of the character you would like to delete? &7(Type cancel to cancel)'
    character-delete-invalid-character: '&cYou do not have a character by that name.'
    character-delete-confirmation: '&fThis operation will be permanent, and you will not be able to recover your character. Are you sure you wish to continue?'
    character-delete-confirmation-invalid-boolean: '&cThat''s not a valid answer.'
    character-delete-valid: '&aCharacter deleted.'
    gender-usage: '&cUsage: /gender [add|remove|list]'
    gender-add-prompt: '&fWhat is the name of the gender you would like to add? &7(Type cancel to cancel)'
    gender-add-invalid-gender: '&cThat gender already exists.'
    gender-add-valid: '&aGender added.'
    gender-remove-prompt: '&fWhat is the name of the gender you would like to remove? &7(Type cancel to cancel)'
    gender-remove-invalid-gender: '&cThat''s not a valid gender.'
    gender-remove-valid: '&aGender removed.'
    gender-list-title: '&fGenders: '
    gender-list-item: '&f- &7$gender'
    race-usage: '&cUsage: /race [add|remove|list]'
    race-add-prompt: '&fWhat is the name of the race you would like to add? &7(Type cancel to cancel)'
    race-add-invalid-race: '&cThat race already exists.'
    race-add-valid: '&aRace added.'
    race-remove-prompt: '&fWhat is the name of the race you would like to remove? &7(Type cancel to cancel)'
    race-remove-invalid-race: '&cThat''s not a valid race.'
    race-remove-valid: '&aRace removed.'
    race-list-title: '&fRaces: '
    race-list-item: '&f- &7$race'
    not-from-console: '&cYou may not use this command from console.'
    operation-cancelled: '&cOperation cancelled.'
    no-character: '&cYou do not currently have an active character. Please create one with /character new, or switch to an old one using /character switch.'
    no-character-other: '&cThis player does not currently have a character.'
    no-permission-character-card-self: '&cYou do not have permission to view your own character card.'
    no-permission-character-card-other: '&cYou do not have permission to view other people''s character cards.'
    no-permission-character-list: '&cYou do not have permission to view your character list.'
    no-permission-character-new: '&cYou do not have permission to create new characters.'
    no-permission-character-set-age: '&cYou do not have permission to set your character''s age.'
    no-permission-character-set-dead: '&cYou do not have permission to set your character''s dead state.'
    no-permission-character-set-dead-yes: '&cYou do not have permission to set your character to be dead.'
    no-permission-character-set-dead-no: '&cYou do not have permission to set your character to be not dead.'
    no-permission-character-set-description: '&cYou do not have permission to set your character''s description.'
    no-permission-character-set-gender: '&cYou do not have permission to set your character''s gender.'
    no-permission-character-set-name: '&cYou do not have permission to set your character''s name.'
    no-permission-character-set-player: '&cYou do not have permission to transfer your character to another player.'
    no-permission-character-set-race: '&cYou do not have permission to set your character''s race.'
    no-permission-character-hide-age: '&cYou do not have permission to hide your character''s age.'
    no-permission-character-hide-description: '&cYou do not have permission to hide your character''s description.'
    no-permission-character-hide-gender: '&cYou do not have permission to hide your character''s gender.'
    no-permission-character-hide-name: '&cYou do not have permission to hide your character''s name.'
    no-permission-character-hide-player: '&cYou do not have permission to hide your character''s player.'
    no-permission-character-hide-race: '&cYou do not have permission to hide your character''s race.'
    no-permission-character-unhide-age: '&cYou do not have permission to unhide your character''s age.'
    no-permission-character-unhide-description: '&cYou do not have permission to unhide your character''s description.'
    no-permission-character-unhide-gender: '&cYou do not have permission to unhide your character''s gender.'
    no-permission-character-unhide-name: '&cYou do not have permission to unhide your character''s name.'
    no-permission-character-unhide-player: '&cYou do not have permission to unhide your character''s player.'
    no-permission-character-unhide-race: '&cYou do not have permission to unhide your character''s race.'
    no-permission-character-switch: '&cYou do not have permission to switch characters.'
    no-permission-character-delete: '&cYou do not have permission to delete characters.'
    no-permission-gender-add: '&cYou do not have permission to add genders.'
    no-permission-gender-remove: '&cYou do not have permission to remove genders.'
    no-permission-gender-list: '&cYou do not have permission to list genders.'
    no-permission-race-add: '&cYou do not have permission to add races.'
    no-permission-race-remove: '&cYou do not have permission to remove races.'
    no-permission-race-list: '&cYou do not have permission to list races.'
    dead-character: '&cYou are dead and can not move.'
characters:
    min-age: 0
    max-age: 10000
    defaults:
        name: 'unset'
        gender: null
        age: 20
        race: null
        description: 'unset'
        dead: false
        inventory-contents: []
        helmet: null
        chestplate: null
        leggings: null
        boots: null
        health: 20
        max-health: 20
        mana: 20
        max-mana: 20
        food-level: 20
        thirst-level: 20
        player-hidden: false
        name-hidden: false
        gender-hidden: false
        age-hidden: false
        race-hidden: false
        description-hidden: false
    view-card-requires-sneak: true
    kill-character-on-death: false
    delete-character-on-death: false
    set-player-display-name: false
    new-character-cooldown: 604800000