name: elysium-stat-lib-bukkit
author: alyphen
version: @version@
main: com.seventh_root.elysium.stats.bukkit.ElysiumStatLibBukkit
depend: [elysium-core-bukkit, elysium-players-bukkit, elysium-characters-bukkit]