name: elysium-bank-lib-bukkit
author: alyphen
version: @version@
main: com.seventh_root.elysium.banks.bukkit.ElysiumBankLibBukkit
depend: [elysium-core-bukkit, elysium-character-lib-bukkit, elysium-economy-lib-bukkit]