messages:
    bank-sign-invalid-operation: '&cThat''s not a valid operation. Please use withdraw, deposit, or balance. (Line 2)'
    bank-sign-invalid-currency: '&cThat''s not a valid currency. Please use a valid currency. (Line 4)'
    bank-withdraw-invalid-wallet-full: '&cYou cannot withdraw that amount, it would not fit in your wallet.'
    bank-withdraw-invalid-not-enough-money: '&cYou cannot withdraw that amount, your bank balance is not high enough.'
    bank-withdraw-valid: '&aWithdrew $amount $currency. Wallet balance: $wallet-balance. Bank balance: $bank-balance.'
    bank-deposit-invalid-not-enough-money: '&cYou cannot deposit that amount, your wallet balance is not high enough.'
    bank-deposit-valid: '&aDeposited $amount $currency. Wallet balance: $wallet-balance. Bank balance: $bank-balance.'
    bank-balance-valid: '&aBalance: $amount $currency'
    no-permission-bank-create: '&cYou do not have permission to create banks.'