name: elysium-payment-lib-bukkit
author: alyphen
version: @version@
main: com.seventh_root.elysium.payments.bukkit.ElysiumPaymentLibBukkit
depend:
- elysium-core-bukkit
- elysium-player-lib-bukkit
- elysium-character-lib-bukkit
- elysium-economy-lib-bukkit
- elysium-bank-lib-bukkit