wand-item:
    ==: org.bukkit.inventory.ItemStack
    v: 1976
    type: STICK
    meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: Wand
        lore:
        - Creates selections
caching:
    rpkit_selection:
        id:
            enabled: true
            size: 20