name: elysium-players-bukkit
version: @version@
main: com.seventh_root.elysium.players.bukkit.ElysiumPlayersBukkit
author: alyphen
description: Elysium Players implementation for Bukkit
depend: [elysium-core-bukkit, elysium-player-lib-bukkit]
softdepend: [elysium-chat-lib-bukkit]
commands:
    account:
        description: |
            Account management command
            /account link [type] [name] - links the account of the given type
        aliases: [acc]
        usage: /<command> [link]
permissions:
    elysium.players.command.account.link:
        description: Allows linking other accounts
        default: true
    elysium.players.command.account.link.irc:
        description: Allows linking IRC account
        default: true
