lock-item:
    ==: org.bukkit.inventory.ItemStack
    type: IRON_INGOT
    meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: Lock
        lore:
        - Used for locking chests
key-item:
    ==: org.bukkit.inventory.ItemStack
    type: IRON_INGOT
    meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: Key
