lock-item:
    ==: org.bukkit.inventory.ItemStack
    type: IRON_INGOT
    meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: Lock
        lore:
        - Used for locking chests
key-item:
    ==: org.bukkit.inventory.ItemStack
    type: IRON_INGOT
    meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: Key
messages:
    block-locked: '&cThe $block appears to be locked. You would need the key to get in.'
    crafting-no-keys: '&cYou may not use keys as a substitute for iron ingots.'
    keyring-invalid-item: '&cYou may not place non-key items on your keyring.'
    lock-successful: '&aBlock locked. You''ve been given the key. Please take good care of it.'
    lock-invalid-already-locked: '&cThat block is already locked.'
    unlock-successful: '&aBlock unlocked.'
    unlock-invalid-no-key: '&cYou must have the key to that block in order to unlock it.'
    unlock-invalid-not-locked: '&cThat block is not locked.'
    get-key-invalid-not-locked: '&cThat block is not locked.'
    get-key-successful: '&aHere is the key.'
    get-key-valid: '&aPlease interact with the block you would like the key for.'
    unlock-valid: '&aPlease interact with the block you would like to unlock.'
    not-from-console: '&cYou must be a player to perform this command.'
    no-character: '&cYou must have a character to perform this action.'
    no-permission-get-key: '&cYou do not have permission to get keys.'
    no-permission-keyring: '&cYou do not have permission to view your keyring.'
    no-permission-unlock: '&cYou do not have permission to remove locks.'