messages:
    auction-usage: '&cUsage: /auction [create]'
    auction-set-currency-prompt: '&fWhich currency would you like to use? &7(Type cancel to cancel)'
    auction-set-currency-prompt-list-item: '&f- &7$currency'
    auction-set-currency-invalid-currency: '&cThat''s not a valid currency.'
    auction-set-currency-valid: '&aCurrency set.'
    auction-set-duration-prompt: '&fHow long would you like the auction to be (in hours)?'
    auction-set-duration-invalid-number: '&cYou must specify a number for the duration.'
    auction-set-duration-invalid-negative: '&cYou may not set the duration to a negative number.'
    auction-set-duration-valid: '&aDuration set.'
    auction-set-start-price-prompt: '&fWhat would you like to set the start price to?'
    auction-set-start-price-invalid-number: '&cYou must specify a number for the start price.'
    auction-set-start-price-invalid-negative: '&cYou may not set the start price to a negative number.'
    auction-set-start-price-valid: '&aStart price set.'
    auction-set-buy-out-price-prompt: '&fWhat would you like to set the buy out price to?'
    auction-set-buy-out-price-invalid-number: '&cYou must specify a number for the buy out price.'
    auction-set-buy-out-price-invalid-negative: '&cYou may not set the buy out price to a negative number.'
    auction-set-buy-out-price-valid: '&aBuy out price set.'
    auction-set-no-sell-price-prompt: '&fWhat would you like to set the no sell price to?'
    auction-set-no-sell-price-invalid-number: '&cYou must specify a number for the no sell price.'
    auction-set-no-sell-price-invalid-negative: '&cYou may not set the no sell price to a negative number.'
    auction-set-no-sell-price-valid: '&aNo sell price set.'
    auction-set-minimum-bid-increment-prompt: '&fWhat would you like to set the minimum bid increment to?'
    auction-set-minimum-bid-increment-invalid-number: '&cYou must specify a number for the minimum bid increment.'
    auction-set-minimum-bid-increment-invalid-negative: '&cYou may not set the minimum bid increment to a negative number.'
    auction-set-minimum-bid-increment-valid: '&aMinimum bid increment set.'
    auction-create-valid: '&aAuction created.'
    auction-create-id: '&aYour auction ID is $id. Please inform bidders to use /bid $id [amount]. You may also create an auction sign with [auction] on the first line and $id on the second line.'
    auction-item-received: '&aReceived $amount $item from $character''s auction (auction ID $auction_id).'
    auction-item-returned: '&aYour $item $amount was returned due to your auction failing (auction ID $auction_id).'
    bid-invalid-not-high-enough: '&cYou must bid at least $amount.'
    bid-invalid-not-enough-money: '&cYou do not have enough money to bid that high.'
    bid-invalid-auction-not-open: '&cThat auction is not currently open.'
    bid-invalid-auction-not-existent: '&cThat auction does not exist.'
    bid-invalid-amount-not-a-number: '&cYou must specify a number for the amount to bid.'
    bid-invalid-auction-id-not-a-number: '&cYou must specify a number for the auction ID.'
    bid-invalid-too-far-away: '&cYou are not close enough to that auction.'
    bid-valid: '&aBid $amount $currency for $item.'
    bid-created: '&a$character bid $amount $currency on auction $auction_id for $item.'
    auction-sign-invalid-id-not-a-number: '&cPlease write the auction ID on the second line.'
    auction-sign-invalid-auction-does-not-exist: '&cThere is no auction with that ID.'
    no-character: '&cYou need a character to perform this action.'
    not-from-console: '&cYou may not use this command from console.'
    operation-cancelled: '&cOperation cancelled.'
auctions:
    radius: 16
