messages:
    money-usage: '&cUsage: /money [subtract|add|set|view|pay|wallet]'
    money-subtract-player-prompt: '&fWhich player would you like to subtract money from? &7(Type cancel to cancel)'
    money-subtract-player-invalid-player: '&cThat player is not online.'
    money-subtract-player-valid: '&aPlayer set.'
    money-subtract-character-prompt: '&fWhich character would you like to subtract money from? &7(Type cancel to cancel)'
    money-subtract-character-prompt-list-item: '&f- &7$character'
    money-subtract-character-invalid-character: '&cThat player does not have a character by that name.'
    money-subtract-character-valid: '&aCharacter set.'
    money-subtract-currency-prompt: '&fWhich currency would you like to use? &7(Type cancel to cancel)'
    money-subtract-currency-prompt-list-item: '&f- &7$currency'
    money-subtract-currency-invalid-currency: '&cThat''s not a valid currency.'
    money-subtract-currency-valid: '&aCurrency set.'
    money-subtract-amount-prompt: '&fHow much money would you like to subtract? &7(Type cancel to cancel)'
    money-subtract-amount-invalid-amount-balance: '&cThat player''s character does not have enough money.'
    money-subtract-amount-invalid-amount-negative: '&cYou may not subtract negative money.'
    money-subtract-amount-invalid-amount-number: '&cYou must specify a number to subtract.'
    money-subtract-amount-valid: '&aAmount set.'
    money-subtract-valid: '&aMoney subtracted.'
    money-add-player-prompt: '&fWhich player would you like to add money to? &7(Type cancel to cancel)'
    money-add-player-invalid-player: '&cThat player is not online.'
    money-add-player-valid: '&aPlayer set.'
    money-add-character-prompt: '&fWhich character would you like to add money to? &7(Type cancel to cancel)'
    money-add-character-prompt-list-item: '&f- &7$character'
    money-add-character-invalid-character: '&cThat player does not have a character by that name.'
    money-add-character-valid: '&aCharacter set.'
    money-add-currency-prompt: '&fWhich currency would you like to use? &7(Type cancel to cancel)'
    money-add-currency-prompt-list-item: '&f- &7$currency'
    money-add-currency-invalid-currency: '&cThat''s not a valid currency.'
    money-add-currency-valid: '&aCurrency set.'
    money-add-amount-prompt: '&fHow much money would you like to add? &7(Type cancel to cancel)'
    money-add-amount-invalid-amount-negative: '&cYou may not add negative money.'
    money-add-amount-invalid-amount-number: '&cYou must specify a number to add.'
    money-add-amount-invalid-amount-limit: '&cThat amount would not fit in the receiver''s wallet.'
    money-add-amount-valid: '&aAmount set.'
    money-add-valid: '&aMoney added.'
    money-set-player-prompt: '&fWhich player would you like to set the balance of? &7(Type cancel to cancel)'
    money-set-player-invalid-player: '&cThat player is not online.'
    money-set-player-valid: '&aPlayer set.'
    money-set-character-prompt: '&fWhich character would you like to set the balance of? &7(Type cancel to cancel)'
    money-set-character-prompt-list-item: '&f- &7$character'
    money-set-character-invalid-character: '&cThat player does not have a character by that name.'
    money-set-character-valid: '&aCharacter set.'
    money-set-currency-prompt: '&fWhich currency would you like to use? &7(Type cancel to cancel)'
    money-set-currency-prompt-list-item: '&f- &7$currency'
    money-set-currency-invalid-currency: '&cThat''s not a valid currency.'
    money-set-currency-valid: '&aCurrency set.'
    money-set-amount-prompt: '&fWhat would you like to set the balance to? &7(Type cancel to cancel)'
    money-set-amount-invalid-amount-negative: '&cYou may not set balance to a negative number.'
    money-set-amount-invalid-amount-number: '&cYou must specify a number to set the balance to.'
    money-set-amount-invalid-amount-limit: '&cThat amount would not fit in the receiver''s wallet.'
    money-set-amount-valid: '&aAmount set.'
    money-set-valid: '&aBalance set.'
    money-view-player-prompt: '&fWhich player would you like to view the balance of?'
    money-view-player-invalid-player: '&cThat player is not online.'
    money-view-player-valid: '&aPlayer set.'
    money-view-character-prompt: '&fWhich character would you like to view money of? &7(Type cancel to cancel)'
    money-view-character-prompt-list-item: '&f- &7$character'
    money-view-character-invalid-character: '&cThat player does not have a character by that name.'
    money-view-character-valid: '&aCharacter set.'
    money-view-currency-prompt: '&fWhich currency would you like to use? &7(Type cancel to cancel)'
    money-view-currency-prompt-list-item: '&f- &7$currency'
    money-view-currency-invalid-currency: '&cThat''s not a valid currency.'
    money-view-currency-valid: '&aCurrency set.'
    money-pay-player-prompt: '&fWhich player would you like to pay? &7(Type cancel to cancel)'
    money-pay-player-invalid-player-offline: '&cThat player is not online.'
    money-pay-player-invalid-player-distance: '&cThat player is too far away to pay.'
    money-pay-player-valid: '&aPlayer set.'
    money-pay-character-prompt: '&fWhich character would you like to pay? &7(Type cancel to cancel)'
    money-pay-character-prompt-list-item: '&f- &7$character'
    money-pay-character-invalid-character: '&cThat player does not have a character by that name.'
    money-pay-character-valid: '&aCharacter set.'
    money-pay-currency-prompt: '&fWhich currency would you like to use? &7(Type cancel to cancel)'
    money-pay-currency-prompt-list-item: '&f- &7$currency'
    money-pay-currency-invalid-currency: '&cThat''s not a valid currency.'
    money-pay-currency-valid: '&aCurrency set.'
    money-pay-amount-prompt: '&fHow much would you like to pay? &7(Type cancel to cancel)'
    money-pay-amount-invalid-amount-balance: '&cYou may not pay more money than you have.'
    money-pay-amount-invalid-amount-negative: '&cYou may not pay a negative amount.'
    money-pay-amount-invalid-amount-number: '&cYou must specify a number to pay'
    money-pay-amount-invalid-amount-limit: '&cThat amount would not fit in the receiver''s wallet.'
    money-pay-amount-valid: '&aAmount set.'
    money-pay-valid: '&aPaid $amount $currency to $character.'
    money-pay-received: '&aReceived $amount $currency from $character.'
    money-view-player-prompt: '&fWhich player would you like to view the money of? &7(Type cancel to cancel)'
    money-view-player-invalid-player: '&cThat player is not online.'
    money-view-player-valid: '&aPlayer set.'
    money-view-character-prompt: '&fWhich character would you like to view the money of? &7(Type cancel to cancel)'
    money-view-character-prompt-list-item: '&f- &7$character'
    money-view-character-invalid-character: '&cThat player does not have a character by that name.'
    money-view-valid: '&fBalance:'
    money-view-valid-list-item: '&7$currency: &f$balance'
    money-wallet-currency-prompt: '&fWhich currency would you like to use?'
    money-wallet-currency-prompt-list-item: '&f- &7$currency'
    money-wallet-currency-invalid-currency: '&cThat''s not a valid currency.'
    money-wallet-currency-valid: '&aCurrency set.'
    money-wallet-valid: '&aOpening wallet...'
    currency-usage: '&cUsage: /currency [add|remove|list]'
    currency-set-name-prompt: '&fWhat is the currency''s name?'
    currency-set-name-invalid-name: '&cA currency by that name already exists.'
    currency-set-name-valid: '&aName set.'
    currency-set-name-singular-prompt: '&fWhat would you like the display name for referring to the currency in it''s singular form to be?'
    currency-set-name-singular-valid: '&aSingular name set.'
    currency-set-name-plural-prompt: '&fWhat would you like the display name for referring to the currency in it''s plural form to be?'
    currency-set-name-plural-valid: '&aPlural name set.'
    currency-set-rate-prompt: '&fWhat would you like to set the rate of conversion to?'
    currency-set-rate-invalid-rate-number: '&cRate must be a number.'
    currency-set-rate-invalid-rate-negative: '&cRate must be greater than zero.'
    currency-set-rate-valid: '&aRate set.'
    currency-set-default-amount-prompt: '&fHow much of this currency would you like new characters to have of this currency by default?'
    currency-set-default-amount-invalid-amount-number: '&cDefault amount must be a number.'
    currency-set-default-amount-invalid-amount-negative: '&cDefault amount cannot be negative.'
    currency-set-default-amount-valid: '&aDefault amount set.'
    currency-set-material-prompt: '&fWhat would you like to use to represent this currency as a physical currency?'
    currency-set-material-invalid-material: '&cThat material is not valid.'
    currency-set-material-valid: '&aMaterial set.'
    currency-add-valid: '&aCurrency created.'
    currency-remove-prompt: '&fWhich currency would you like to remove?'
    currency-remove-invalid-currency: '&cThat currency does not exist.'
    currency-remove-valid: '&aCurrency removed.'
    currency-list-title: '&fCurrencies:'
    currency-list-item: '&f- &7$currency'
    not-from-console: '&cYou may not use this command from console.'
    operation-cancelled: '&cOperation cancelled.'
    no-permission-money-subtract: '&cYou do not have permission to subtract money.'
    no-permission-money-add: '&cYou do not have permission to add money.'
    no-permission-money-set: '&cYou do not have permission to set money.'
    no-permission-money-view-self: '&cYou do not have permission to view your own money.'
    no-permission-money-view-other: '&cYou do not have permission to view other people''s money'
    no-permission-money-pay: '&cYou do not have permission to pay people money.'
    no-permission-money-wallet: '&cYou do not have permission to open your wallet.'
    no-permission-currency-add: '&cYou do not have permission to add currencies.'
    no-permission-currency-remove: '&cYou do not have permission to remove currencies.'
    no-permission-currency-list: '&cYou do not have permission to list currencies.'
    no-character: '&cYou need a character to transfer money. Please create one.'
    recipient-no-character: '&cThe recipient needs a character to transfer money to. Please get them to create one.'
payments:
    maximum-distance: 8
currency:
    default: null
