messages:
    chatchannel-usage: '&cUsage: /chatchannel [join|leave|create|delete|speak|list|set]'
    chatchannel-join-prompt: '&fWhich chat channel would you like to join? &7(Type cancel to cancel)'
    chatchannel-join-invalid-chatchannel: '&cInvalid chat channel.'
    chatchannel-join-valid: '&aChat channel joined.'
    chatchannel-leave-prompt: '&fWhich chat channel would you like to leave? &7(Type cancel to cancel)'
    chatchannel-leave-invalid-chatchannel: '&cInvalid chat channel.'
    chatchannel-leave-valid: '&aChat channel left.'
    chatchannel-create-prompt: '&fWhat would you like to call the chat channel? &7(Type cancel to cancel)'
    chatchannel-create-valid: '&aChat channel created.'
    chatchannel-delete-prompt: '&fWhich chat channel would you like to delete? &7(Type cancel to cancel)'
    chatchannel-delete-invalid-chatchannel: '&cInvalid chat channel.'
    chatchannel-delete-valid: '&aChat channel deleted.'
    chatchannel-speak-prompt: '&fWhich chat channel would you like to speak in? &7(Type cancel to cancel)'
    chatchannel-speak-invalid-chatchannel: '&cInvalid chat channel.'
    chatchannel-speak-valid: '&aNow speaking in $channel'
    chatchannel-set-usage: '&cUsage: /chatchannel set [name|colour|format|radius|clearradius|matchpattern|ircenabled|ircchannel|ircwhitelist|joinedbydefault]'
    chatchannel-set-chatchannel-prompt: '&fWhich chat channel would you like to modify? &7(Type cancel to cancel)'
    chatchannel-set-chatchannel-invalid-chatchannel: '&cInvalid chat channel.'
    chatchannel-set-name-prompt: '&fWhat would you like to set the chat channel name to? &7(Type cancel to cancel)'
    chatchannel-set-name-invalid-name: '&cA chat channel by that name already exists.'
    chatchannel-set-name-valid: '&aName set.'
    chatchannel-set-color-prompt: '&fWhat would you like to set the chat channel colour to? &7(Type cancel to cancel)'
    chatchannel-set-color-invalid-color: '&cInvalid colour.'
    chatchannel-set-color-valid: '&aColour set.'
    chatchannel-set-formatstring-prompt: '&fWhat format would you like messages to appear in? Use $message, $sender-prefix, $sender-player, $sender-character, $receiver-prefix, $receiver-player, $receiver-character, $colour and $channel variables. Use the ampersand for colour codes. &7(Type cancel to cancel)'
    chatchannel-set-formatstring-valid: '&aFormat string set.'
    chatchannel-set-radius-prompt: '&fWhat would you like to set the chat channel radius to? Specify zero or a negative value for a global channel. &7(Type cancel to cancel)'
    chatchannel-set-radius-valid: '&aRadius set.'
    chatchannel-set-clear-radius-prompt: '&fWhat would you like the maximum radius where chat messages are completely clear to be? Specify zero or a negative value to disable garble. &7(Type cancel to cancel)'
    chatchannel-set-clear-radius-valid: '&aClear radius set.'
    chatchannel-set-match-pattern-prompt: '&fWhat would you like to set the channel match pattern to? Specify a regex with at least one capture group. Type ''none'' to disable match patterns. &7(Type cancel to cancel)'
    chatchannel-set-match-pattern-valid: '&aMatch pattern set.'
    chatchannel-set-irc-enabled-prompt: '&fWould you like to enable IRC for this channel? &7(Type cancel to cancel)'
    chatchannel-set-irc-enabled-invalid-boolean: '&cThat''s not a valid answer.'
    chatchannel-set-irc-enabled-valid: '&aIRC enabled/disabled set.'
    chatchannel-set-irc-channel-prompt: '&fWhich IRC channel would you like to associate this chat channel with? &7(Type cancel to cancel)'
    chatchannel-set-irc-channel-invalid-irc-channel: '&cThat''s not a valid IRC channel.'
    chatchannel-set-irc-channel-valid: '&aIRC channel set.'
    chatchannel-set-irc-whitelist-prompt: '&fWould you like to whitelist the IRC channel? &7(Type cancel to cancel)'
    chatchannel-set-irc-whitelist-invalid-boolean: '&cThat''s not a valid answer.'
    chatchannel-set-irc-whitelist-valid: '&aIRC channel whitelist state set.'
    chatchannel-set-joined-by-default-prompt: '&fShould the channel be joined by default? &7(Type cancel to cancel)'
    chatchannel-set-joined-by-default-invalid-boolean: '&cThat''s not a valid answer.'
    chatchannel-set-joined-by-default-valid: '&aDefault join state set.'
    chatchannel-list-title: '&fChat channels:'
    chatchannel-list-item: '&f- $color$name'
    irc-register-valid: 'Registered. Please check your email for the verification code to complete the verification process.'
    irc-register-invalid-email-invalid: 'You did not specify a valid email.'
    irc-register-invalid-email-not-specified: 'You must specify an email.'
    irc-verify-valid: 'Attempted to verify. If you correctly entered the verification code, I should now be verified.'
    irc-verify-invalid-verification-code-not-specified: 'You must specify the registration code from your email.'
    irc-quit: 'Server shut down.'
    prefix-usage: '&cUsage: /prefix [add|remove|list]'
    prefix-add-valid: '&aPrefix added.'
    prefix-set-name-prompt: '&fWhat would you like to name the prefix? (This will be used in the permission node and for lookups)'
    prefix-set-name-invalid-name: '&cA prefix by that name already exists.'
    prefix-set-name-valid: '&aName set.'
    prefix-set-prefix-prompt: '&fWhat would you like to set the prefix to? (This is what will be displayed in chat)'
    prefix-set-prefix-valid: '&aPrefix set.'
    prefix-remove-valid: '&aPrefix removed.'
    prefix-remove-invalid-prefix: '&cA prefix by that name does not exist.'
    prefix-remove-prompt: '&fWhich prefix would you like to remove?'
    prefix-list-title: '&fPrefixes:'
    prefix-list-item: '&f- $prefix'
    snoop-usage: '&cUsage: /snoop [on|off|check]'
    snoop-enabled: '&aSnooping enabled.'
    snoop-already-enabled: '&cSnooping was already enabled.'
    snoop-disabled: '&aSnooping disabled.'
    snoop-already-disabled: '&cSnooping was already disabled.'
    snoop-check-on: '&aSnooping is enabled.'
    snoop-check-off: '&aSnooping is disabled.'
    chat-group-create-valid: '&aChat group created. Use /chatgroup invite $group [player] to invite players.'
    chat-group-create-invalid-reserved: '&cChat groups starting with _pm_ are reserved. Please choose a different name.'
    chat-group-create-invalid-taken: '&cA chat group by that name already exists. Please choose a different name.'
    chat-group-create-usage: '&cUsage: /chatgroup create [name]'
    chat-group-disband-valid: '&aChat group $group disbanded.'
    chat-group-disband-invalid-nonexistent: '&cNo chat group by that name exists.'
    chat-group-disband-usage: '&cUsage: /chatgroup disband [name]'
    chat-group-invite-received: '&aYou have been invited to chat group $group. Use /chatgroup join $group to join.'
    chat-group-invite-valid: '&aYou invited $player to the chat group $group.'
    chat-group-invite-invalid-player: '&cNo player by that name is online.'
    chat-group-invite-invalid-not-a-member: '&cYou are not a member of that chat group.'
    chat-group-invite-invalid-chat-group: '&cNo chat group by that name exists.'
    chat-group-invite-usage: '&cUsage: /chatgroup invite [name] [player]'
    chat-group-join-received: '&a$player joined $group.'
    chat-group-join-valid: '&aJoined chat group $group.'
    chat-group-join-invalid-no-invite: '&cYou have not been invited to that chat group.'
    chat-group-join-invalid-chat-group: '&cNo chat group by that name exists.'
    chat-group-join-usage: '&cUsage: /chatgroup join [name]'
    chat-group-leave-valid: '&aLeft chat group $group.'
    chat-group-leave-invalid-not-a-member: '&cYou are not a member of that chat group.'
    chat-group-leave-invalid-chat-group: '&cNo chat group by that name exists.'
    chat-group-leave-usage: '&cUsage: /chatgroup leave [name]'
    chat-group-message-invalid-not-a-member: '&cYou are not a member of that chat group.'
    chat-group-message-invalid-chat-group: '&cNo chat group by that name exists.'
    chat-group-message-usage: '&cUsage: /chatgroup message [name] [message]'
    chat-group-members-list-title: '&aMembers:'
    chat-group-members-list-item: '&f- &7$player'
    chat-group-invitations-list-title: '&aPending invitations:'
    chat-group-invitations-list-item: '&f- &7$player'
    chat-group-members-invalid-chat-group: '&cNo chat group by that name exists.'
    chat-group-members-usage: '&cUsage: /chatgroup members [name]'
    chat-group-usage: '&cUsage: /chatgroup [create|disband|invite|join|leave|message|players]'
    reply-usage: '&cUsage: /reply [group] [message]'
    reply-invalid-chat-group: '&cYou have not used a chat group or private messaged anyone recently.'
    message-invalid-target: '&cNo chat group or player by that name exists.'
    message-invalid-self: '&cYou cannot message yourself.'
    message-usage: '&cUsage: /message [target] [message]'
    not-from-console: '&cYou may not use this command from console.'
    operation-cancelled: '&cOperation cancelled.'
    no-chat-channel: '&cYou are not currently speaking in a chat channel. Please list channels with /chatchannel list and then speak in one using /chatchannel speak.'
    no-chat-channels-available: '&cThere are no chat channels available. Please create one with /chatchannel create.'
    no-permission-chatchannel-create: '&cYou do not have permission to create chat channels.'
    no-permission-chatchannel-delete: '&cYou do not have permission to delete chat channels.'
    no-permission-chatchannel-join: '&cYou do not have permission to join chat channels.'
    no-permission-chatchannel-leave: '&cYou do not have permission to leave chat channels.'
    no-permission-chatchannel-join-channel: '&cYou do not have permission to join $channel.'
    no-permission-chatchannel-leave-channel: '&cYou do not have permission to leave $channel.'
    no-permission-chatchannel-list-channel: '&cYou do not have permission to list chat channels.'
    no-permission-chatchannel-set: '&cYou do not have permission to modify chat channels.'
    no-permission-chatchannel-set-name: '&cYou do not have permission to modify a chat channel''s name.'
    no-permission-chatchannel-set-color: '&cYou do not have permission to modify a chat channel''s colour.'
    no-permission-chatchannel-set-format: '&cYou do not have permission to modify a chat channel''s format.'
    no-permission-chatchannel-set-radius: '&cYou do not have permission to modify a chat channel''s radius.'
    no-permission-chatchannel-set-clearradius: '&cYou do not have permission to modify a chat channel''s clear radius.'
    no-permission-chatchannel-set-matchpattern: '&cYou do not have permission to modify a chat channel''s match pattern.'
    no-permission-chatchannel-set-ircenabled: '&cYou do not have permission to enable or disable IRC for a chat channel.'
    no-permission-chatchannel-set-ircchannel: '&cYou do not have permission to modify a chat channel''s IRC channel.'
    no-permission-chatchannel-set-ircwhitelist: '&cYou do not have permission to modify a chat channel''s IRC whitelist setting.'
    no-permission-chatchannel-set-joinedbydefault: '&cYou do not have permission to make a chat channel joined by default.'
    no-permission-chatchannel-speak: '&cYou do not have permission to speak in channels.'
    no-permission-chatchannel-speak-channel: '&cYou do not have permission to speak in $channel.'
    no-permission-prefix-add: '&cYou do not have permission to add prefixes.'
    no-permission-prefix-remove: '&cYou do not have permission to remove prefixes.'
    no-permission-prefix-list: '&cYou do not have permission to list prefixes.'
    no-permission-snoop-on: '&cYou do not have permission to enable snooping.'
    no-permission-snoop-off: '&cYou do not have permission to disable snooping.'
    no-permission-snoop-check: '&cYou do not have permission to check whether you are snooping.'
    no-permission-chat-group: '&cYou do not have permission to use chat group commands.'
    no-permission-chat-group-create: '&cYou do not have permission to create chat groups.'
    no-permission-chat-group-disband: '&cYou do not have permission to disband chat groups.'
    no-permission-chat-group-invite: '&cYou do not have permission to invite people to chat groups.'
    no-permission-chat-group-join: '&cYou do not have permission to join chat groups.'
    no-permission-chat-group-leave: '&cYou do not have permission to leave chat groups.'
    no-permission-chat-group-members: '&cYou do not have permission to list chat group members.'
    no-permission-chat-group-message: '&cYou do not have permission to message chat groups.'
    no-permission-message: '&cYou do not have permission to send private messages.'
    no-permission-reply: '&cYou do not have permission to reply to messages.'
    no-message: '&cFailed to send message due to lack of message.'
    no-character: '&cThat channel requires you to have an active character.'
    no-channel: '&cFailed to send message due to missing channel.'
    command-snoop: '&2[command] $sender-player: $command'
irc:
    name: 'elysium'
    real-name: 'elysium'
    login: 'elysium'
    cap-enabled: true
    auto-nick-change-enabled: true
    auto-split-message-enabled: false
    server: 'chat.freenode.net:6667'
    password: 'change_me'
chat-group:
    format: '&8[$group] $sender-player: &f$message'
