name: elysium-chat-bukkit
version: @version@
main: com.seventh_root.elysium.chat.bukkit.ElysiumChatBukkit
author: alyphen
description: Elysium Chat implementation for Bukkit
depend: [elysium-core-bukkit, elysium-players-bukkit, elysium-characters-bukkit]
commands:
    chatchannel:
        description: |
            Chat channel management command
            /chatchannel join - Joins a channel
            /chatchannel leave - Leaves a channel
            /chatchannel create - Creates a channel
            /chatchannel delete - Deletes a channel
            /chatchannel speak - Speaks in a channel
            /chatchannel list - Lists the chat channels
            /chatchannel set - Modifies a chat channel
        aliases: [channel, chan, ch]
        usage: /<command> [join|leave|create|delete|speak|list|set]
permissions:
    elysium.chat.command.chatchannel.create:
        description: Allows creating chat channels
        default: op
    elysium.chat.command.chatchannel.delete:
        description: Allows deleting chat channels
        default: op
    elysium.chat.command.chatchannel.join:
        description: Allows joining chat channels
        default: true
    elysium.chat.command.chatchannel.join.[channel]:
        description: Allows joining a specific chat channel
        default: op
    elysium.chat.command.chatchannel.leave:
        description: Allows leaving chat channels
        default: true
    elysium.chat.command.chatchannel.leave.[channel]:
        description: Allows leaving a specific chat channel
        default: op
    elysium.chat.command.chatchannel.list:
        description: Allows listing chat channels
        default: true
    elysium.chat.command.chatchannel.set:
        description: Allows modifying chat channels
        default: op
    elysium.chat.command.chatchannel.set.name:
        description: Allows modifying a chat channel name
        default: op
    elysium.chat.command.chatchannel.set.color:
        description: Allows modifying a chat channel colour
        default: op
    elysium.chat.command.chatchannel.set.format:
        description: Allows modifying a chat channel format
        default: op
    elysium.chat.command.chatchannel.set.radius:
        description: Allows modifying a chat channel radius
        default: op
    elysium.chat.command.chatchannel.set.clearradius:
        description: Allows modifying a chat channel clear radius
        default: op
    elysium.chat.command.chatchannel.set.matchpattern:
        description: Allows modifying a chat channel match pattern
        default: op
    elysium.chat.command.chatchannel.set.ircenabled:
        description: Allows enabling or disabling IRC for a chat channel
        default: op
    elysium.chat.command.chatchannel.set.ircchannel:
        description: Allows modifying a chat channel IRC channel
        default: op
    elysium.chat.command.chatchannel.set.ircwhitelist:
        description: Allows enabling or disabling IRC whitelisting for an IRC channel
        default: op
    elysium.chat.command.chatchannel.set.joinedbydefault:
        description: Allows enabling or disabling making this channel a default channel
        default: op
    elysium.chat.command.chatchannel.speak:
        description: Allows speaking in chat channels
        default: true
    elysium.chat.command.chatchannel.speak.[channel]:
        description: Allows speaking in a specific chat channel
        default: op